### ISSUE TITLE
PSR-15 progress tracker in Expressive modules

### ISSUE THREAD

**Issue by webimpress** [zendframework/zend-expressive#528]
Created issue here to track progress on updating expressive modules to support PSR-15.
It is not yet approved but in it is in the last phase and probably it will be approved and released in Jan 2018. If everything will be fine, the namespace will be only changed (and package name obv). Here is the list modules with associated PR with PSR-15 support which needs update. All (?) of these modules required major release, as this update is BC break. Minimum PHP requirement also is bumped to PHP 7.1 (in modules where it was PHP 5.6):

- [x] https://github.com/zendframework/zend-expressive-router/pull/39
- [x] https://github.com/zendframework/zend-expressive-helpers/pull/50
- [x] https://github.com/zendframework/zend-stratigility/pull/122
- [x] https://github.com/zendframework/zend-problem-details/pull/22
- [x] https://github.com/zendframework/zend-expressive-session/pull/14
- [x] https://github.com/zendframework/zend-expressive-authentication/pull/3
- [x] https://github.com/zendframework/zend-expressive-flash/pull/3 - requires: `zend-expressive-session`
- [x] https://github.com/zendframework/zend-expressive-csrf/pull/3 - requires: `zend-expressive-flash` and `zend-expressive-session`,
- [x] https://github.com/zendframework/zend-expressive-platesrenderer/pull/27 **[no bc break]** - requires: `zend-expressive-helpers` and `zend-expressive-router`,
- [x] https://github.com/zendframework/zend-expressive-authentication-oauth2/pull/5 - requires: `zend-expressive-authentication`,
- [x] https://github.com/zendframework/zend-expressive-authorization/pull/11 - requires: `zend-expressive-router` and `zend-expressive-authentication`
- [x] [zendframework/zend-expressive#529](https://github.com/zendframework/zend-expressive/pull/529) - requires: `zend-expressive-router` and `zend-stratigility`,
- [x] https://github.com/zendframework/zend-expressive-tooling/pull/39 - requires `zend-expressive`, `zend-expressive-router` and `zend-stratiglity`,
- [x] zendframework/zend-expressive-skeleton

See also: https://discourse.zendframework.com/t/psr-15-compatibility-issues-and-proposal/378

**Comment by mano87** [comment]
Is there any news here?

**Comment by webimpress** [comment]
@mano87 https://github.com/zendframework/zend-expressive/pull/543

**Comment by weierophinney** [comment]
And, probably a better place to look is the Expressive v3 project in the zend-expressive-skeleton repository, as it tracks other related issues:

- https://github.com/zendframework/zend-expressive-skeleton/projects/1

Right now, the time frame for final release is 4-6 weeks (end of February/mid-March).

**Comment by xtreamwayz** [comment]
Closing this as all related PSR-15 PR's are merged.

**Comment by froschdesign** [comment]
Next time: GitHub Project! 😃

**Comment by xtreamwayz** [comment]
Or ask someone to create it for you: https://github.com/zendframework/zend-expressive-skeleton/projects/1

**Comment by webimpress** [comment]
@froschdesign @xtreamwayz When I've created that "issue tracker" the project wasn't used in zend repositories (at least not in expressive) and many people didn't know if it is going ot be public. Don't blame now, please, for opening that issue :)

**Comment by weierophinney** [comment]
@froschdesign At the time, I wasn't aware (and I'm not sure how many were) that projects on _repositories_ are public, and that they can refer to issues/PRs in _other_ repositories.

Now we know! So we can do things differently next time — and we actually have a few of these open _now_!
